### 과제 1

In [75]:
import numpy as np

In [77]:
matrix_a = np.array([[1,0,2],[0,1,1],[1,2,2]])
matrix_E = np.identity(3)

matrix_b = np.dot(matrix_a,np.linalg.inv(2*matrix_E-matrix_a))
print(matrix_b)

[[ 0.  -2.  -1. ]
 [-0.5  0.  -0.5]
 [-0.5 -1.  -1.5]]


### 과제 2

In [80]:
matrix_a = np.array([[2,-1,-3],[-1,-2,-3],[1,1,4]])
matrix_a_inverse = np.linalg.inv(matrix_a)
b = np.array([[2],[-1],[1]])

x = np.dot(matrix_a_inverse,b)
x

array([[1.],
       [0.],
       [0.]])

In [82]:
try:
    matrix_a = np.array([[2,-1,-3],[-4,2,6],[3,1,4]])
    matrix_a_inverse = np.linalg.inv(matrix_a)
    b = np.array([[2],[-1],[1]])

    x = np.dot(matrix_a_inverse,b)
    x
except:
    print('A는 특이 행렬이므로 역행렬을 가지지 않는다.')

A는 특이 행렬이므로 역행렬을 가지지 않는다.


### 과제 3

In [83]:
def f(array):
    return np.array(list(array[i,j] for i in range(0,len(array)) for j in range(0,len(array))))

In [84]:
f(np.array([[1,2],[2,3]]))

array([1, 2, 2, 3])

In [85]:
f(np.array([[1,2,3],[2,3,4],[3,4,5]]))

array([1, 2, 3, 2, 3, 4, 3, 4, 5])

### 과제 4

In [86]:
matrix_a = np.array([[0.6, 0.3], [0.4, 0.7]])

init_vector = np.array([0, 1])

In [87]:
x0 = init_vector
print(x0)

[0 1]


In [88]:
x1 = matrix_a.dot(x0)
print(x1)

[0.3 0.7]


In [89]:
x2 = matrix_a.dot(x1)
print(x2)

[0.39 0.61]


### 과제 5

In [90]:
def x(t):
    matix_a = np.array([[0.6, 0.3],
                        [0.4, 0.7]])
    init_vector = np.array([1, 0])

    if t == 0:
        xt = init_vector
        return xt
    
    else:
        xt = init_vector
        for i in range(t):
            xt = matrix_a.dot(xt)
        return xt

In [91]:
print('10개월후의 사자의 예상위치: ',x(10))
print('영역 2에 있을 확률이 높다')

10개월후의 사자의 예상위치:  [0.4285748 0.5714252]
영역 2에 있을 확률이 높다
